import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/ThemeProvider'
import { Toaster } from 'sonner'
import { AuthProvider } from '@/providers/AuthProvider'

import { authOptions } from '@/lib/auth'
import { getServerSession } from 'next-auth'
import { db } from '@/lib/db'
import { EdgeStoreProvider } from '@/lib/edgestore'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getData(userId: string) {
  if (userId) {
    const data = await db.user.findUnique({
      where: {
        id: userId,
      },
      select: {
        colorScheme: true,
      },
    })
    return data
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  const user = session?.user
  const data = await getData(user?.id as string)

  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body
          className={`${inter.className} ${data?.colorScheme ?? 'theme-orange'}`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <EdgeStoreProvider>
              {children}
              <Toaster
                toastOptions={{
                  unstyled: true,
                  classNames: {
                    error: 'bg-red-400',
                    success: 'text-green-400',
                    warning: 'text-yellow-400',
                    info: 'bg-blue-400',
                  },
                }}
              />
            </EdgeStoreProvider>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  )
}
